# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: smileev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: SolHealth-BE

custom:
  wsgi:
    app: app.app
  dotenv:
    logging: false

provider:
  name: aws
  stage: dev
  runtime: python3.12
  region: us-east-2
  architecture: x86_64
  iam:
    role:
      statements:
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::therapists-personal-data/*'

package:
  exclude:
    - node_modules/**
    - .venv/**
    - .github/**
    - .idea/**

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin
