# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: smileev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: SolHealth-BE

custom:
  wsgi:
    app: app.app
  dotenv:
    logging: false
  pythonRequirements:
    noDeploy:
      - pip
      - bin
      - pytest
  customDomain:
    domainName: 'api.dev.solhealth.co'
    createRoute53Record: true
    createRoute53IPv6Record: true
    certificateName: 'dev.solhealth.co'
    apiType: rest
    autoDomain: true
  customCertificate:
    hostedZoneIds: 'Z0565774GWNT1OIQP463'
    certificateName: 'dev.solhealth.co'
    region: us-east-1
    subjectAlternativeNames:
      - 'api.dev.solhealth.co'

provider:
  name: aws
  stage: dev
  runtime: python3.12
  region: us-east-2
  architecture: x86_64
  timeout: 10
  iam:
    role:
      statements:
        # Allow functions to connect to DB
        - Effect: Allow
          Action:
            - 'dsql:DbConnectAdmin'
          Resource:
            - 'arn:aws:dsql:us-east-2:762233746762:cluster/s4abt2gmvgate3uokdmhw2l7by'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::therapists-personal-data/*'

package:
  exclude:
    - node_modules/**
    - .venv/**
    - .github/**
    - .idea/**
    - tests/**
    - .ruff_cache/**

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-certificate-creator
