name: Generate Python Class
description: Generates a Python class from JSON
inputs:
  typeform_ids:
    description: "Typeform IDs JSON"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate Python class from JSON
      shell: bash
      env:
        TYPEFORM_IDS: ${{ inputs.typeform_ids }}
      run: |
        echo "Generating Python class..."

        # Creating Python-script for class generation
        cat <<EOF > generate_class.py
        import json
        import os

        # Static class generation
        json_data = '''$TYPEFORM_IDS'''
        data = json.loads(json_data)

        class_content = "class TypeformIds:\\n"
        for key, value in data.items():
            class_content += f"    {key.upper()} = \\"{value}\\"\\n"

        # Creating dir, if it doesn't exist
        os.makedirs("src/utils/typeform", exist_ok=True)

        # Saving class to file
        with open("src/utils/typeform/typeform_ids.py", "w") as f:
            f.write(class_content)
        EOF

        # Running script
        python generate_class.py

        # Checking
        cat src/utils/typeform/typeform_ids.py