name: be deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-24.04
    environment: develop
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22.13.0'
      - name: Install node dependencies
        run: |
          npm ci
          npm install -g serverless

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create .env file
        run: |
          eval "echo \"$(cat .example.env)\"" > .env

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install python dependencies
        run: uv sync

      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version

      - name: Install Plugin and deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          serverless deploy