name: be deploy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - name: Checkout Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version

#      - name: Install Plugin and deploy
#        uses: serverless/github-action@v3.2
#        with:
#          args: -c "python3 --version && serverless plugin install --name serverless-python-requirements && serverless plugin install --name serverless-wsgi && serverless deploy --stage dev"
#          entrypoint: /bin/sh
#        env:
#          SLS_INTERACTIVE_SETUP_ENABLE: 1
#          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
