name: CI - Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint code
    secrets: inherit
    uses: ./.github/workflows/lint.yml
  tests:
    name: Run tests
    secrets: inherit
    uses: ./.github/workflows/tests.yml
