name: Lint code

on:
  workflow_call:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install python dependencies
        run: uv sync

      - name: Ruff check
        run: uv run ruff check --output-format=full --show-fixes ./src
      - name: Ruff format
        run: uv run ruff format --check ./src
