name: Run tests

on:
  workflow_call:

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    environment: 'dev'

    services:
      postgres: # we need a postgres docker image to be booted a side car service to run the tests that needs a db
        image: postgres
        env: # the environment variable must match with app/settings.py if block of DATBASES variable otherwise test will fail due to connectivity issue.
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432 # exposing 5432 port for application to use
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: ./.github/actions/generate-class
        with:
          typeform_ids: ${{ vars.TYPEFORM_IDS }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install python dependencies
        run: uv sync

      - name: Run test
        run: uv run pytest
        env:
          RDS_USER: postgres
          RDS_PASSWORD: postgres
          RDS_DATABASE: github-actions
          RDS_HOST: 127.0.0.1
          RDS_PORT: 5432

